language: node_js
node_js:
  - 'node'
cache:
  npm: false
  directories:
    - '~/.pnpm-store'
before_install:
  - curl -f https://get.pnpm.io/v6.js | node - add --global pnpm@6
  - pnpm config set store-dir ~/.pnpm-store
install:
  - pnpm install
deploy:
  provider: script
  script: pnpm run deploy
  skip_cleanup: true
  on:
    branch: master
